export * from './articlePage';
export * from './authPage';
export * from './globalfeedPage';
export * from './mainPage';
export * from './newarticlePage';
export * from './profilePage';
export * from './profilesettingsPage';
export * from './registerPage';
export * from './yourfeedPage';